// packages/vue/src/code-gloss.component.ts
import { defineComponent, h, type PropType } from 'vue';
import type {
	Annotation,
	CodeGlossConfig,
	CodeGlossStyleOverrides,
	Connection,
	Highlighter,
} from 'codegloss';
import { styleOverridesToCssVars } from 'codegloss';
import { stripUndefined } from './strip-undefined.util';

/**
 * Stateless Vue 3 wrapper around the `<code-gloss>` custom element. Renders
 * the WC with a `<script type="application/json">` child containing the
 * serialized config — exactly the same shape the React wrapper produces.
 *
 * Vue's runtime is happy to render arbitrary tag names via `h()`, so this
 * works without any `app.config.compilerOptions.isCustomElement` configuration
 * at the consumer site (that flag is only needed when authoring template
 * syntax that mentions the custom element directly).
 */
export const CodeGloss = defineComponent({
	name: 'CodeGloss',
	props: {
		code: { type: String, required: true },
		lang: { type: String, required: true },
		filename: { type: String, default: undefined },
		theme: { type: String, default: undefined },
		annotations: {
			type: Array as PropType<Annotation[]>,
			default: undefined,
		},
		connections: {
			type: Array as PropType<Connection[]>,
			default: undefined,
		},
		highlight: {
			type: Function as PropType<Highlighter>,
			default: undefined,
		},
		styleOverrides: {
			type: Object as PropType<CodeGlossStyleOverrides>,
			default: undefined,
		},
	},
	setup(props) {
		return () => {
			const result = props.highlight?.(props.code, props.lang);
			const highlightedHtml =
				typeof result === 'string' ? result : result?.html;
			const highlightBackground =
				typeof result === 'object' ? result?.background : undefined;
			const highlightColor =
				typeof result === 'object' ? result?.color : undefined;

			const payload: CodeGlossConfig = {
				code: props.code,
				lang: props.lang,
				filename: props.filename,
				annotations: props.annotations,
				connections: props.connections,
				highlightedHtml,
				highlightBackground,
				highlightColor,
			};
			// Strip undefined keys so the serialized payload matches the React
			// wrapper byte-for-byte for the common case.
			const json = JSON.stringify(stripUndefined(payload));

			const styleVars = styleOverridesToCssVars(props.styleOverrides);
			const hostAttrs: Record<string, unknown> = {};
			if (props.theme) hostAttrs.theme = props.theme;
			if (styleVars.length > 0) {
				hostAttrs.style = Object.fromEntries(styleVars);
			}

			return h('code-gloss', hostAttrs, [
				h('script', {
					type: 'application/json',
					innerHTML: json,
				}),
			]);
		};
	},
});

// packages/react/src/code-gloss.component.tsx
import React from 'react';
import { styleOverridesToCssVars } from 'codegloss';
import type { CodeGlossProps } from './code-gloss.types';

export function CodeGloss(props: CodeGlossProps): React.ReactElement {
	const { theme, highlight, styleOverrides, ...rest } = props;
	let configProps = rest;

	if (highlight && rest.highlightedHtml === undefined) {
		const result = highlight(rest.code, rest.lang);
		configProps =
			typeof result === 'string'
				? { ...rest, highlightedHtml: result }
				: {
						...rest,
						highlightedHtml: result.html,
						...(result.background
							? { highlightBackground: result.background }
							: {}),
						...(result.color ? { highlightColor: result.color } : {}),
					};
	}

	const json = JSON.stringify(configProps);
	const styleVars = styleOverridesToCssVars(styleOverrides);
	const styleProp =
		styleVars.length > 0
			? (Object.fromEntries(styleVars) as React.CSSProperties)
			: undefined;

	const hostProps: Record<string, unknown> = {};
	if (theme) hostProps.theme = theme;
	if (styleProp) hostProps.style = styleProp;

	return React.createElement(
		'code-gloss',
		Object.keys(hostProps).length > 0 ? hostProps : undefined,
		React.createElement('script', {
			type: 'application/json',
			dangerouslySetInnerHTML: { __html: json },
		}),
	);
}
